version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/api-server"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
    labels:
      - "dependabot"
      - "deps"
      - "app(api)"
    reviewers:
      - "hwakabh"
  - package-ecosystem: "npm"
    directory: "/web-frontend"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
    labels:
      - "dependabot"
      - "deps"
      - "app(ui)"
    reviewers:
      - "hwakabh"
  - package-ecosystem: github-actions
    directory: /.github
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependabot"
      - "deps"
      - "ci"
    reviewers:
      - "hwakabh"
