# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/api-server"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependabot"
      - "deps"
      - "app(api)"
    reviewers:
      - "hwakabh"
  - package-ecosystem: "npm"
    directory: "/web-frontend"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependabot"
      - "deps"
      - "app(ui)"
    reviewers:
      - "hwakabh"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependabot"
      - "deps"
      - "ci"
    reviewers:
      - "hwakabh"
