changelog:
  exclude:
    labels:
      - release
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Frontend changes
      labels:
        - app(ui)
    - title: Backend changes
      labels:
        - app(api)
    - title: API Schemas
      labels:
        - schemas
    - title: Bug Fixes
      labels:
        - bugs
    - title: Security Fixes
      labels:
        - security
    - title: Dependencies Updates
      labels:
        - deps
        - dependabot
    - title: Other Changes
      labels:
        - "*"
