changelog:
  exclude:
    labels:
      - release
  categories:
    - title: Breaking Changes
      labels:
        - breaking-changes
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bugs
    - title: Security Fixes
      labels:
        - security
    - title: Dependencies Updates
      labels:
        - deps
        - dependabot
    - title: Other Changes
      labels:
        - "*"
