# File matches
app(api):
- changed-files:
  - any-glob-to-any-file: ['api-server/**']

app(ui):
- changed-files:
  - any-glob-to-any-file: ['web-frontend/**']

ci:
- changed-files:
  - any-glob-to-any-file: ['.github/**/*']
- head-branch: ['^ci/']

deps:
- changed-files:
  - any-glob-to-any-file: ['api-server/package.json', 'web-frontend/package.json', 'schema/package.json']
- head-branch: ['^dependabot/']

docs:
- changed-files:
  - any-glob-to-any-file: ['**/README.md', 'app-diagram.drawio.svg']

schemas:
- changed-files:
  - any-glob-to-any-file: ['schemas/**/*']

tests:
- changed-files:
  - any-glob-to-any-file: ['api-server/test/**/*']
  - any-glob-to-any-file: ['web-frontend/test/**/*']


# Branch name matches
dependabot:
- head-branch: ['^dependabot/']

bugs:
- head-branch: ['^fix/', '^hotfix/']
