name: Backend CI
on:
  push:
    # branches:
    #   - main
    # All updates except api-server/** will be ignored
    paths:
      - 'api-server/**'
  workflow_dispatch:

jobs:
  image_build_and_push:
    name: Build & Ship OCI image
    runs-on: ubuntu-latest

    # For Workload Identity
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pack
        uses: buildpacks/github-actions/setup-pack@v5.0.0
        # https://github.com/buildpacks/github-actions#setup-pack-cli-action

      - name: Verify pack version
        run: |
          pack version

      # Google Cloud buildpacks
      #   https://cloud.google.com/docs/buildpacks/builders
      #   https://cloud.google.com/docs/buildpacks/nodejs
      - name: Publish packages
        run: |
          pack build ghcr.io/hwakabh/gh-pages-api:latest \
            --builder gcr.io/buildpacks/builder:latest \
            --path ./api-server/ \
            --publish

      # https://github.com/google-github-actions/auth
      - name: Auth with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/1037550336239/locations/global/workloadIdentityPools/default-pool/providers/default-provider'
          service_account: 'gh-action-cloudrun@hwakabh-dev.iam.gserviceaccount.com'

      # https://github.com/google-github-actions/deploy-cloudrun
      - uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          image: 'ghcr.io/hwakabh/gh-pages-api:latest'
          service: 'gh-pages-api-server'
