name: Backend CI
on:
  push:
    branches:
      - main
    # All updates except api-server/** will be ignored
    paths:
      - 'api-server/**'
  workflow_dispatch:

env:
  MAIL_API_KEY: ${{ secrets.MAIL_API_KEY }}

jobs:
  image_build_and_push:
    name: Build & Ship OCI image
    runs-on: ubuntu-latest

    # For Workload Identity
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pack
        uses: buildpacks/github-actions/setup-pack@v5.5.4
        # https://github.com/buildpacks/github-actions#setup-pack-cli-action

      # https://github.com/google-github-actions/auth
      - name: Auth with Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/1037550336239/locations/global/workloadIdentityPools/default-pool/providers/default-provider'
          service_account: 'gh-action-cloudrun@hwakabh-dev.iam.gserviceaccount.com'
          token_format: access_token

      # https://github.com/docker/login-action#google-artifact-registry-gar
      # Note that Cloud Run supports only GAR(GCR) and DockerHub
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      # Google Cloud buildpacks
      #   https://cloud.google.com/docs/buildpacks/builders
      #   https://cloud.google.com/docs/buildpacks/nodejs
      - name: Publish packages
        run: |
          pack build us-central1-docker.pkg.dev/hwakabh-dev/gh-pages/api:latest \
            --builder gcr.io/buildpacks/builder:latest \
            --path ./api-server/ \
            --publish

      # https://github.com/google-github-actions/deploy-cloudrun
      - uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          image: 'us-central1-docker.pkg.dev/hwakabh-dev/gh-pages/api:latest'
          service: 'gh-pages-api-server'
          env_vars: |
            MAIL_API_KEY=${{ env.MAIL_API_KEY }}

