name: Backend CI
on:
  push:
    branches:
      - main
    # All updates except api-server/** will be ignored
    paths:
      - 'api-server/**'
  workflow_dispatch:

jobs:
  image_build_and_push:
    name: Build & Ship OCI image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # # TODO: To be implemented
      # # https://github.com/google-github-actions/deploy-cloudrun
      # - name: Deploy to Cloud Run
