name: Backend CI
on:
  push:
    branches:
      - main
    # All updates except api-server/** will be ignored
    paths:
      - 'api-server/**'
  workflow_dispatch:

jobs:
  image_build_and_push:
    name: Build & Ship OCI image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pack
        uses: buildpacks/github-actions/setup-pack@v5.0.0
        # https://github.com/buildpacks/github-actions#setup-pack-cli-action

      - name: Verify pack version
        run: |
          pack version

      # Google Cloud buildpacks
      #   https://cloud.google.com/docs/buildpacks/builders
      #   https://cloud.google.com/docs/buildpacks/nodejs
      - name: Publish packages
        run: |
          pack build ghcr.io/hwakabh/gh-pages-api:latest \
            --builder gcr.io/buildpacks/builder:latest \
            --path ./api-server/ \
            --publish

      # # TODO: To be implemented
      # # https://github.com/google-github-actions/deploy-cloudrun
      # - name: Deploy to Cloud Run
