name: Build CI

on:
  pull_request:
    branches:
      - '**'
      - '!main'
      - '!releases'
    paths:
      - 'api-server/**'
      - 'web-frontend/**'
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Filter Path
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: '.github/config/paths-filter.yaml'
        # https://github.com/dorny/paths-filter

      # Run only for Backend
      - name: Install pack
        if: steps.filter.outputs.api == 'true'
        uses: buildpacks/github-actions/setup-pack@v5.5.3

      - name: Build Express App
        if: steps.filter.outputs.api == 'true'
        run: |
          pack build us-central1-docker.pkg.dev/hwakabh-dev/gh-pages/api:latest \
            --builder gcr.io/buildpacks/builder:latest \
            --path ./api-server/

      # Run only for Frontend
      - name: Setup node.js environment
        if: steps.filter.outputs.ui == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 17.3.0

      - name: Build Vite App
        if: steps.filter.outputs.ui == 'true'
        working-directory: ./web-frontend
        run: |
          npm ci && npx vite build
