name: Frontend CI
on:
  push:
    branches:
      - main
    # All updates except web-frontend/** will be ignored
    paths:
      - 'web-frontend/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build Vue app and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: yarn install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: --cwd ./web-frontend install

      - name: yarn build to /docs
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: --cwd ./web-frontend build --dest ../docs
          # Build vue app with outside of app-root

      - name: Deploy to GitHub Pages to branch/gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
