name: Frontend CI
on:
  push:
    branches:
      - releases
    # All updates except web-frontend/** will be ignored
    paths:
      - 'web-frontend/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build Vue app and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 17.3.0

      - name: Install packages with CI pipeline
        run: npm ci
        working-directory: ./web-frontend

      - name: Build vue-app to /docs
        run: npx vite build --outDir ../docs
        working-directory: ./web-frontend
          # Build vue app with outside of app-root

      - name: Deploy to GitHub Pages to branch/gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
