name: Frontend CI
on:
  push:
    branches:
      - releases
    # All updates except web-frontend/** will be ignored
    paths:
      - 'web-frontend/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Vue app and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 17.3.0

      - name: Install packages with CI pipeline
        run: npm ci
        working-directory: ./web-frontend

      - name: Build vue-app to /docs
        run: npx vite build
        working-directory: ./web-frontend
          # Build vue app with outside of app-root

      - name: Upload as artifacts for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./web-frontend/dist
          retention-days: 3

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages from artifacts
        id: deployment
        uses: actions/deploy-pages@v4.0.4
