name: PR for release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  git_pr_release:
    name: git-pr-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make release PR
        uses: bakunyo/git-pr-release-action@master
        env:
          TZ: "Asia/Tokyo"
          GITHUB_TOKEN: ${{ secrets.PAT_GIT_PR_RELEASE }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: releases
          GIT_PR_RELEASE_BRANCH_STAGING: main
          GIT_PR_RELEASE_TEMPLATE: .github/PULL_REQUEST_TEMPLATE/release-pr-template.erb
          GIT_PR_RELEASE_LABELS: release
