name: Build Vue Apps with yarn
on:
  push:
    branches:
      - main
    paths:
      - 'web-frontend/**'
  pull_request:
    paths:
      - 'web-frontend/**'
jobs:
  build_and_update:
    name: Build Vue app and push new staticfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git source
        uses: actions/checkout@v2
      - name: Install npm package
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: --cwd ./web-frontend install # will run `yarn install` command
      - name: Generate static file to /docs
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: --cwd ./web-frontend build --dest ../docs
      - name: Update /docs with commmit
        env:
          GIT_EMAIL_DOMAIN: users.noreply.github.com
          DEPLOY_URL_DOMAIN: github.com
        run: |
          git config --local user.name "hwakabh"
          git config --local user.email "hwakabh@${{ env.GIT_EMAIL_DOMAIN }}"
          git add ./docs
          git commit --message "Updated staticifiles."
