name: Tests and Build CI

on:
  pull_request:
    # triggered only when PR created with its target to main
    branches:
      - 'main'
    paths:
      - 'api-server/**'
      - 'web-frontend/**'
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-24.04

    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Filter Path
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: '.github/config/paths-filter.yaml'
        # https://github.com/dorny/paths-filter

      - name: Setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      # Run only for Backend
      - name: Install dependencies
        if: steps.filter.outputs.api == 'true'
        working-directory: ./api-server
        run: |
          npm ci

      - name: Run Jest
        if: steps.filter.outputs.api == 'true'
        working-directory: ./api-server
        run: |
          npx jest

      # Run only for Frontend
      - name: Install dependencies
        if: steps.filter.outputs.ui == 'true'
        working-directory: ./web-frontend
        run: |
          npm ci

      - name: Run Vitest for compoenent testings
        if: steps.filter.outputs.ui == 'true'
        working-directory: ./web-frontend
        run: |
          npx vitest run

  build-apps:
    name: Build Apps
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Filter Path
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: '.github/config/paths-filter.yaml'
        # https://github.com/dorny/paths-filter

      # Run only for Backend
      - name: Install pack
        if: steps.filter.outputs.api == 'true'
        uses: buildpacks/github-actions/setup-pack@v5.9.3

      - name: Build Express App
        if: steps.filter.outputs.api == 'true'
        run: |
          pack build ghcr.io/hwakabh/gh-pages-api:local \
            --builder gcr.io/buildpacks/builder:latest \
            --path ./api-server/

      # Run only for Frontend
      - name: Install dependencies
        if: steps.filter.outputs.ui == 'true'
        working-directory: ./web-frontend
        run: |
          npm ci

      - name: Build Vite App
        if: steps.filter.outputs.ui == 'true'
        working-directory: ./web-frontend
        env:
          VITE_API_ENDPOINT: ${{ secrets.VITE_API_ENDPOINT }}
        run: |
          npx vite build
