name: Tests CI

on:
  pull_request:
    # triggered only when PR created with its target to main
    branches:
      - 'main'
    paths:
      - 'api-server/**'
      - 'web-frontend/**'
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Filter Path
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: '.github/config/paths-filter.yaml'
        # https://github.com/dorny/paths-filter

      - name: Setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      # Run only for Backend
      - name: Install dependencies
        if: steps.filter.outputs.api == 'true'
        working-directory: ./api-server
        run: |
          npm ci

      - name: Run Jest
        if: steps.filter.outputs.api == 'true'
        working-directory: ./api-server
        run: |
          npx jest

      # Run only for Frontend
      - name: Install dependencies
        if: steps.filter.outputs.ui == 'true'
        working-directory: ./web-frontend
        run: |
          npm ci

      - name: Run Vitest for compoenent testings
        if: steps.filter.outputs.ui == 'true'
        working-directory: ./web-frontend
        run: |
          npx vitest run
