name: Triage Issue

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  triage_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Label Issue
      uses: github/issue-labeler@v3.4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/config/issue-labeler.yaml
        # case if we have multiple configs
        enable-versioned-regex: 0
        # only checks issue titles
        include-title: 1
        include-body: 0
      # https://github.com/github/issue-labeler
