name: Triage PR

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  triage-pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Assign author to PR
        if: github.event.action == 'opened'
        uses: technote-space/assign-author@v1.6.2
        # https://github.com/technote-space/assign-author

      # - name: Set default assignee
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PR_NUMBER: ${{ github.event.number }}
      #   run: |
      #     curl -s -L \
      #       -X POST \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer ${GITHUB_TOKEN}" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/assignees" \
      #       -d '{"assignees":["hwakabh"]}'

      - name: Label to PR
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
          configuration-path: .github/config/pr-labeler.yaml
